import '../models/product.dart';
import 'product_datasource.dart';

class MockProductDatasource implements ProductDatasource {
  @override
  Future<List<Product>> getProducts() async {
    await Future.delayed(const Duration(milliseconds: 600));
    return _products;
  }
}

const List<Product> _products = [
  Product(
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    shortDescription: 'Titane, puce A17 Pro et écran 6,1" ProMotion.',
    description:
        "L'iPhone 15 Pro est le premier iPhone en titane aérospatial, alliant légèreté et robustesse. Doté de la puce A17 Pro, il offre des performances de console de jeux, une caméra professionnelle 48 MP avec zoom optique 5x et une autonomie exceptionnelle. Son écran Super Retina XDR ProMotion avec Always-On s'adapte à tous vos usages.",
    imageUrl: 'https://picsum.photos/seed/iphone15pro/600/600',
    category: 'Smartphones',
    brand: 'Apple',
    price: 1299,
    oldPrice: 1399,
    discount: 10,
    rating: 4.8,
    reviewCount: 352,
    stock: 25,
    isAvailable: true,
    colors: ['#000000', '#4C5563', '#C7C7CC', '#A8A29E'],
    sizes: [],
    images: [
      'https://picsum.photos/seed/iphone15pro/600/600',
      'https://picsum.photos/seed/iphone15pro2/600/600',
      'https://picsum.photos/seed/iphone15pro3/600/600',
    ],
    specifications: {
      'Écran': '6,1" Super Retina XDR',
      'Puce': 'A17 Pro',
      'RAM': '8 Go',
      'Stockage': '256 Go',
      'Batterie': '3274 mAh',
      'Caméra': '48 MP',
    },
  ),
  Product(
    id: 'galaxy-s24',
    name: 'Samsung Galaxy S24',
    shortDescription: 'IA Galaxy, écran 6,2" et 7 ans de mises à jour.',
    description:
        'Le Galaxy S24 intègre Galaxy AI pour une traduction instantanée, une recherche entourée et des éditions photo intelligentes. Son écran Dynamic AMOLED 2X 120 Hz et son grand capteur 50 MP capturent chaque détail, de jour comme de nuit.',
    imageUrl: 'https://picsum.photos/seed/galaxys24/600/600',
    category: 'Smartphones',
    brand: 'Samsung',
    price: 899,
    oldPrice: 999,
    discount: 10,
    rating: 4.6,
    reviewCount: 214,
    stock: 40,
    isAvailable: true,
    colors: ['#000000', '#4B5158', '#9E79A9', '#E3E0C7'],
    sizes: [],
    images: [
      'https://picsum.photos/seed/galaxys24/600/600',
      'https://picsum.photos/seed/galaxys24b/600/600',
      'https://picsum.photos/seed/galaxys24c/600/600',
    ],
    specifications: {
      'Écran': '6,2" Dynamic AMOLED 2X',
      'Puce': 'Exynos 2400',
      'RAM': '8 Go',
      'Stockage': '256 Go',
      'Batterie': '4000 mAh',
      'Caméra': '50 MP',
    },
  ),
  Product(
    id: 'macbook-air-m3',
    name: 'MacBook Air M3',
    shortDescription: 'Puce M3, écran Liquid Retina 13,6", 18 h d\'autonomie.',
    description:
        'Le MacBook Air M3 redéfinit la mobilité : ultra-fin, silencieux et incroyablement rapide. La puce M3 débloque des performances jusqu’à 1,6x plus rapides que M1, parfaites pour le code, la création et la bureautique. Jusqu’à 18 heures d’autonomie sur une seule charge.',
    imageUrl: 'https://picsum.photos/seed/macbookair/600/600',
    category: 'Laptops',
    brand: 'Apple',
    price: 1199,
    oldPrice: 1349,
    discount: 11,
    rating: 4.9,
    reviewCount: 187,
    stock: 15,
    isAvailable: true,
    colors: ['#2E3B4A', '#E3DFD8', '#D4D5D9', '#5A6068'],
    sizes: [],
    images: [
      'https://picsum.photos/seed/macbookair/600/600',
      'https://picsum.photos/seed/macbookairb/600/600',
      'https://picsum.photos/seed/macbookairc/600/600',
    ],
    specifications: {
      'Écran': '13,6" Liquid Retina',
      'Puce': 'Apple M3',
      'RAM': '8 Go',
      'Stockage': '256 Go SSD',
      'Batterie': '18 h',
      'Poids': '1,24 kg',
    },
  ),
  Product(
    id: 'dell-xps-13',
    name: 'Dell XPS 13',
    shortDescription: 'Ultrabook fin, Intel Core i7 et châssis aluminium.',
    description:
        'Le Dell XPS 13 combine un châssis CNC en aluminium, un écran InfinityEdge et le processeur Intel Core de 13e génération. Son clavier rétroéclairé et sa connectique complète en font le compagnon idéal des professionnels exigeants.',
    imageUrl: 'https://picsum.photos/seed/dellxps/600/600',
    category: 'Laptops',
    brand: 'Dell',
    price: 1049,
    oldPrice: 1199,
    discount: 12,
    rating: 4.5,
    reviewCount: 96,
    stock: 20,
    isAvailable: true,
    colors: ['#C7C7C7', '#1F1F1F'],
    sizes: [],
    images: [
      'https://picsum.photos/seed/dellxps/600/600',
      'https://picsum.photos/seed/dellxpsb/600/600',
      'https://picsum.photos/seed/dellxpsc/600/600',
    ],
    specifications: {
      'Écran': '13,4" Full HD+',
      'Processeur': 'Intel Core i7-1360P',
      'RAM': '16 Go',
      'Stockage': '512 Go SSD',
      'Batterie': '12 h',
      'Poids': '1,17 kg',
    },
  ),
  Product(
    id: 'playstation-5',
    name: 'PlayStation 5',
    shortDescription: 'SSD 1 To, ray tracing et manette DualSense.',
    description:
        'La PlayStation 5 offre des temps de chargement quasi nuls grâce à son SSD ultra-rapide, un ray tracing immersif et la manette DualSense au retour haptique révolutionnaire. Plongez au cœur de vos jeux avec la console la plus puissante de Sony.',
    imageUrl: 'https://picsum.photos/seed/ps5/600/600',
    category: 'Gaming',
    brand: 'Sony',
    price: 549,
    oldPrice: 599,
    discount: 8,
    rating: 4.7,
    reviewCount: 412,
    stock: 10,
    isAvailable: true,
    colors: ['#FFFFFF', '#1F1F1F'],
    sizes: [],
    images: [
      'https://picsum.photos/seed/ps5/600/600',
      'https://picsum.photos/seed/ps5b/600/600',
      'https://picsum.photos/seed/ps5c/600/600',
    ],
    specifications: {
      'Stockage': '1 To SSD',
      'GPU': 'AMD RDNA 2',
      'Résolution': 'Jusqu’à 8K',
      'Connectivité': 'HDMI 2.1',
      'Manette': 'DualSense',
      'Poids': '3,9 kg',
    },
  ),
  Product(
    id: 'xbox-series-x',
    name: 'Xbox Series X',
    shortDescription: '12 TFLOPs, 4K natif et Quick Resume.',
    description:
        'La Xbox Series X est la console la plus puissante de Microsoft : 12 téraflops de puissance, des jeux en 4K 120 FPS et la technologie Quick Resume qui vous permet de basculer entre plusieurs jeux instantanément. Profitez aussi du Game Pass.',
    imageUrl: 'https://picsum.photos/seed/xboxx/600/600',
    category: 'Gaming',
    brand: 'Microsoft',
    price: 499,
    oldPrice: 549,
    discount: 9,
    rating: 4.6,
    reviewCount: 278,
    stock: 12,
    isAvailable: true,
    colors: ['#000000'],
    sizes: [],
    images: [
      'https://picsum.photos/seed/xboxx/600/600',
      'https://picsum.photos/seed/xboxxb/600/600',
      'https://picsum.photos/seed/xboxxc/600/600',
    ],
    specifications: {
      'Stockage': '1 To SSD',
      'GPU': 'AMD RDNA 2 — 12 TFLOPs',
      'Résolution': '4K 120 FPS',
      'Connectivité': 'HDMI 2.1',
      'Quick Resume': 'Oui',
      'Poids': '4,45 kg',
    },
  ),
  Product(
    id: 'airpods-pro-2',
    name: 'AirPods Pro 2',
    shortDescription: 'Réduction de bruit 2x plus efficace, puce H2.',
    description:
        'Les AirPods Pro 2 offrent une réduction active du bruit deux fois plus efficace, un son haute fidélité grâce à la puce H2 et un mode transparence adaptatif. Résistants à l’eau et à la transpiration, avec jusqu’à 30 h d’autonomie avec le boîtier.',
    imageUrl: 'https://picsum.photos/seed/airpodspro/600/600',
    category: 'Audio',
    brand: 'Apple',
    price: 249,
    oldPrice: 299,
    discount: 17,
    rating: 4.7,
    reviewCount: 523,
    stock: 60,
    isAvailable: true,
    colors: ['#FFFFFF'],
    sizes: [],
    images: [
      'https://picsum.photos/seed/airpodspro/600/600',
      'https://picsum.photos/seed/airpodsprob/600/600',
      'https://picsum.photos/seed/airpodsproc/600/600',
    ],
    specifications: {
      'Réduction de bruit': 'Active (2x)',
      'Puce': 'Apple H2',
      'Autonomie': '6 h (30 h avec boîtier)',
      'Résistance': 'IPX4',
      'Bluetooth': '5.3',
      'Poids': '5,3 g',
    },
  ),
  Product(
    id: 'sony-wh1000xm5',
    name: 'Sony WH-1000XM5',
    shortDescription: 'Le meilleur casque à réduction de bruit, 30 h.',
    description:
        'Le WH-1000XM5 de Sony est la référence absolue de la réduction de bruit. Ses huit microphones et son processeur HD Noise Canceling QN1 éliminent le monde extérieur, tandis que ses transducteurs 30 mm offrent un son d’une clarté exceptionnelle.',
    imageUrl: 'https://picsum.photos/seed/sonyxm5/600/600',
    category: 'Audio',
    brand: 'Sony',
    price: 349,
    oldPrice: 399,
    discount: 13,
    rating: 4.8,
    reviewCount: 301,
    stock: 30,
    isAvailable: true,
    colors: ['#000000', '#E5E5E5'],
    sizes: [],
    images: [
      'https://picsum.photos/seed/sonyxm5/600/600',
      'https://picsum.photos/seed/sonyxm5b/600/600',
      'https://picsum.photos/seed/sonyxm5c/600/600',
    ],
    specifications: {
      'Réduction de bruit': 'Active (8 micros)',
      'Autonomie': '30 h',
      'Bluetooth': '5.2',
      'Charge rapide': '3 min = 3 h',
      'Poids': '250 g',
      'Pliable': 'Oui',
    },
  ),
  Product(
    id: 'denim-jacket',
    name: 'Denim Jacket Levi’s',
    shortDescription: 'Veste en jean intemporelle, coupe classique.',
    description:
        'La veste en jean classique Levi’s, taillée dans un denim épais et durable, se patine magnifiquement avec le temps. Boutons en métal, poches poitrine et coupe intemporelle : l’indispensable de toutes les garde-robes.',
    imageUrl: 'https://picsum.photos/seed/denimjacket/600/600',
    category: 'Fashion',
    brand: 'Levi’s',
    price: 79,
    oldPrice: 99,
    discount: 20,
    rating: 4.4,
    reviewCount: 88,
    stock: 35,
    isAvailable: true,
    colors: ['#3B5B8C', '#1F1F1F'],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [
      'https://picsum.photos/seed/denimjacket/600/600',
      'https://picsum.photos/seed/denimjacketb/600/600',
      'https://picsum.photos/seed/denimjacketc/600/600',
    ],
    specifications: {
      'Matière': '100% coton',
      'Coupe': 'Classique',
      'Fermeture': 'Boutons métal',
      'Poches': '4 poches',
      'Entretien': 'Lavage 30°',
    },
  ),
  Product(
    id: 'classic-sneakers',
    name: 'Classic Sneakers',
    shortDescription: 'Baskets iconiques en cuir, semelle crème.',
    description:
        'Des baskets en cuir blanc intemporelles, avec une semelle crème et des détails cousus à la main. Confortables au quotidien, elles se portent avec tout : jean, chino ou robe.',
    imageUrl: 'https://picsum.photos/seed/sneakers/600/600',
    category: 'Fashion',
    brand: 'Nike',
    price: 119,
    oldPrice: 139,
    discount: 14,
    rating: 4.6,
    reviewCount: 154,
    stock: 28,
    isAvailable: true,
    colors: ['#FFFFFF', '#000000', '#C7C7C7'],
    sizes: ['39', '40', '41', '42', '43', '44'],
    images: [
      'https://picsum.photos/seed/sneakers/600/600',
      'https://picsum.photos/seed/sneakersb/600/600',
      'https://picsum.photos/seed/sneakersc/600/600',
    ],
    specifications: {
      'Matière': 'Cuir + textile',
      'Semelle': 'Gomme crème',
      'Poids': '280 g',
      'Fermeture': 'Lacets',
      'Entretien': 'Chiffon humide',
    },
  ),
  Product(
    id: 'galaxy-watch-6',
    name: 'Galaxy Watch 6',
    shortDescription: 'Montre connectée AMOLED, GPS et santé 24/7.',
    description:
        'La Galaxy Watch 6 surveille votre santé en continu : fréquence cardiaque, sommeil, ECG et pression artérielle. Son écran AMOLED 1,3" et sa batterie longue durée en font le parfait compagnon sportif.',
    imageUrl: 'https://picsum.photos/seed/galaxywatch/600/600',
    category: 'Accessories',
    brand: 'Samsung',
    price: 299,
    oldPrice: 349,
    discount: 14,
    rating: 4.5,
    reviewCount: 132,
    stock: 45,
    isAvailable: true,
    colors: ['#000000', '#C7C7C7'],
    sizes: ['40 mm', '44 mm'],
    images: [
      'https://picsum.photos/seed/galaxywatch/600/600',
      'https://picsum.photos/seed/galaxywatchb/600/600',
      'https://picsum.photos/seed/galaxywatchc/600/600',
    ],
    specifications: {
      'Écran': 'AMOLED 1,3"',
      'Batterie': '425 mAh',
      'Résistance': '5 ATM',
      'GPS': 'Oui',
      'Compatibilité': 'Android',
      'Capteurs': 'ECG + SpO2',
    },
  ),
  Product(
    id: 'leather-backpack',
    name: 'Leather Backpack',
    shortDescription: 'Sac à dos cuir pour ordinateur 15,6".',
    description:
        'Un sac à dos en cuir véritable, au design élégant et fonctionnel. Compartiment rembourré pour ordinateur 15,6", poches anti-vol et dos respirant. Parfait pour le bureau comme pour les voyages.',
    imageUrl: 'https://picsum.photos/seed/backpack/600/600',
    category: 'Accessories',
    brand: 'Herschel',
    price: 69,
    oldPrice: 89,
    discount: 22,
    rating: 4.3,
    reviewCount: 67,
    stock: 40,
    isAvailable: true,
    colors: ['#6B4A2B', '#000000'],
    sizes: [],
    images: [
      'https://picsum.photos/seed/backpack/600/600',
      'https://picsum.photos/seed/backpackb/600/600',
      'https://picsum.photos/seed/backpackc/600/600',
    ],
    specifications: {
      'Capacité': '20 L',
      'Ordinateur': 'Jusqu’à 15,6"',
      'Matière': 'Cuir véritable',
      'Poches': '2 anti-vol',
      'Poids': '900 g',
    },
  ),
];
